---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: testkube-tests
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mcortinas/testkube-flux
